version: '3.1'

services:

  db:
    container_name: holiwell-db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: holiwell-app
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - pgadmin

  tg:
    build:
      context: .
    env_file:
      - .env
    environment:
      - HOLIWELL_APP_HOST=app
      - HOLIWELL_APP_PORT=8000
    container_name: holiwell-tg
    command: bash -c "python bot.py"
    ports:
      - "8001:8001"
    depends_on:
      - app


  pgadmin:
    container_name: holiwell-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

  