"""empty message

Revision ID: 102638c6db21
Revises: 2f1a77e8122f
Create Date: 2024-03-31 01:02:02.085958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102638c6db21'
down_revision: Union[str, None] = '2f1a77e8122f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('path_to_cover', sa.String(), nullable=True))
    op.add_column('lesson', sa.Column('path_to_video', sa.String(), nullable=True))
    op.add_column('lesson', sa.Column('path_to_audio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'path_to_audio')
    op.drop_column('lesson', 'path_to_video')
    op.drop_column('lesson', 'path_to_cover')
    # ### end Alembic commands ###
