"""links_cascade_1more

Revision ID: 7a833b8ae4f7
Revises: 746d872b3ea4
Create Date: 2024-06-23 21:30:10.266583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a833b8ae4f7'
down_revision: Union[str, None] = '746d872b3ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('link_before_lesson_lesson_id_fkey', 'link_before_lesson', type_='foreignkey')
    op.drop_constraint('link_before_lesson_linked_lesson_id_fkey', 'link_before_lesson', type_='foreignkey')
    op.create_foreign_key(None, 'link_before_lesson', 'lesson', ['linked_lesson_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'link_before_lesson', 'lesson', ['lesson_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link_before_lesson', type_='foreignkey')
    op.drop_constraint(None, 'link_before_lesson', type_='foreignkey')
    op.create_foreign_key('link_before_lesson_linked_lesson_id_fkey', 'link_before_lesson', 'lesson', ['linked_lesson_id'], ['id'])
    op.create_foreign_key('link_before_lesson_lesson_id_fkey', 'link_before_lesson', 'lesson', ['lesson_id'], ['id'])
    # ### end Alembic commands ###
