"""empty message

Revision ID: f4f8a20f4498
Revises: da1cb9790d07
Create Date: 2024-05-01 15:15:05.700447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f8a20f4498'
down_revision: Union[str, None] = 'da1cb9790d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('path_to_avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'path_to_avatar')
    # ### end Alembic commands ###
